# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from src.protos.python.image_processing import image_processing_pb2 as src_dot_protos_dot_python_dot_image__processing_dot_image__processing__pb2


class ImageProcessorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_size = channel.unary_unary(
                '/ImageProcessor/get_size',
                request_serializer=src_dot_protos_dot_python_dot_image__processing_dot_image__processing__pb2.FrameImg.SerializeToString,
                response_deserializer=src_dot_protos_dot_python_dot_image__processing_dot_image__processing__pb2.ImgSize.FromString,
                )
        self.show = channel.unary_unary(
                '/ImageProcessor/show',
                request_serializer=src_dot_protos_dot_python_dot_image__processing_dot_image__processing__pb2.FrameData.SerializeToString,
                response_deserializer=src_dot_protos_dot_python_dot_image__processing_dot_image__processing__pb2.EmptyResponse.FromString,
                )
        self.resize = channel.unary_unary(
                '/ImageProcessor/resize',
                request_serializer=src_dot_protos_dot_python_dot_image__processing_dot_image__processing__pb2.ResizeRequest.SerializeToString,
                response_deserializer=src_dot_protos_dot_python_dot_image__processing_dot_image__processing__pb2.FrameImg.FromString,
                )


class ImageProcessorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_size(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def show(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def resize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageProcessorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_size': grpc.unary_unary_rpc_method_handler(
                    servicer.get_size,
                    request_deserializer=src_dot_protos_dot_python_dot_image__processing_dot_image__processing__pb2.FrameImg.FromString,
                    response_serializer=src_dot_protos_dot_python_dot_image__processing_dot_image__processing__pb2.ImgSize.SerializeToString,
            ),
            'show': grpc.unary_unary_rpc_method_handler(
                    servicer.show,
                    request_deserializer=src_dot_protos_dot_python_dot_image__processing_dot_image__processing__pb2.FrameData.FromString,
                    response_serializer=src_dot_protos_dot_python_dot_image__processing_dot_image__processing__pb2.EmptyResponse.SerializeToString,
            ),
            'resize': grpc.unary_unary_rpc_method_handler(
                    servicer.resize,
                    request_deserializer=src_dot_protos_dot_python_dot_image__processing_dot_image__processing__pb2.ResizeRequest.FromString,
                    response_serializer=src_dot_protos_dot_python_dot_image__processing_dot_image__processing__pb2.FrameImg.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ImageProcessor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ImageProcessor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_size(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ImageProcessor/get_size',
            src_dot_protos_dot_python_dot_image__processing_dot_image__processing__pb2.FrameImg.SerializeToString,
            src_dot_protos_dot_python_dot_image__processing_dot_image__processing__pb2.ImgSize.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def show(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ImageProcessor/show',
            src_dot_protos_dot_python_dot_image__processing_dot_image__processing__pb2.FrameData.SerializeToString,
            src_dot_protos_dot_python_dot_image__processing_dot_image__processing__pb2.EmptyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def resize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ImageProcessor/resize',
            src_dot_protos_dot_python_dot_image__processing_dot_image__processing__pb2.ResizeRequest.SerializeToString,
            src_dot_protos_dot_python_dot_image__processing_dot_image__processing__pb2.FrameImg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
