# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/protos/python/image_processing/image_processing.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9src/protos/python/image_processing/image_processing.proto\"\x1b\n\x08\x46rameImg\x12\x0f\n\x07img_pkl\x18\x01 \x01(\x0c\"1\n\tFrameData\x12\x0f\n\x07img_pkl\x18\x01 \x01(\x0c\x12\x13\n\x0bwindow_name\x18\x02 \x01(\t\"(\n\x07ImgSize\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\"\x0f\n\rEmptyResponse\"?\n\rResizeRequest\x12\x0f\n\x07img_pkl\x18\x01 \x01(\x0c\x12\x1d\n\x0btarget_size\x18\x02 \x01(\x0b\x32\x08.ImgSize2z\n\x0eImageProcessor\x12\x1f\n\x08get_size\x12\t.FrameImg\x1a\x08.ImgSize\x12\"\n\x04show\x12\n.FrameData\x1a\x0e.EmptyResponse\x12#\n\x06resize\x12\x0e.ResizeRequest\x1a\t.FrameImgb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.protos.python.image_processing.image_processing_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FRAMEIMG']._serialized_start=61
  _globals['_FRAMEIMG']._serialized_end=88
  _globals['_FRAMEDATA']._serialized_start=90
  _globals['_FRAMEDATA']._serialized_end=139
  _globals['_IMGSIZE']._serialized_start=141
  _globals['_IMGSIZE']._serialized_end=181
  _globals['_EMPTYRESPONSE']._serialized_start=183
  _globals['_EMPTYRESPONSE']._serialized_end=198
  _globals['_RESIZEREQUEST']._serialized_start=200
  _globals['_RESIZEREQUEST']._serialized_end=263
  _globals['_IMAGEPROCESSOR']._serialized_start=265
  _globals['_IMAGEPROCESSOR']._serialized_end=387
# @@protoc_insertion_point(module_scope)
